### Info: https://gohugo.io/content-management/multilingual/#configure-languages

#[en]
  #languagename = "English"
  #languageflag = "ğŸ‡¬ğŸ‡§"
  #languagecode = "en"
  #languagecodecountry = "DO_NOT_USE"
  #timeZone = "Etc/UTC"
  #weight = 110

[en-ph]
  languagename = "English (PH)"
  languageflag = "ğŸ‡µğŸ‡­"
  languagecode = "en-PH"
  languagecodecountry = "ph"
  timeZone = "Asia/Manila"
  weight = 111
  [en-ph.params]
  [[en-ph.menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1
  [[en-ph.menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
  [[en-ph.menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 6
  [[en-ph.menu.main]]
    name              = "YourOnly.Oneâ„¢"
    identifier        = "yoo-home"
    url               = "https://im.youronly.one"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 8

#[fil]
  #languageName = "Filipino"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "fil"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 120
  #title = ""
  #[fil.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 121
  #title = ""
  #[tl.tglg.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hans"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ja]
  languagename = "æ—¥æœ¬èª"
  languageflag = "ğŸ‡¯ğŸ‡µ"
  languagecode = "ja"
  languagecodecountry = "jp"
  timeZone = "Asia/Tokyo"
  weight = 140
  title = "é›ªã®ä¸–ç•Œ"
  [ja.params]
    description = "ç¤¾ä¼šå‡çµã—ã€åˆ†æã—ã¾ã—ãŸã€‚"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [ja.params.meta]
    description         = "ç¤¾ä¼šå‡çµã—ã€åˆ†æã—ã¾ã—ãŸã€‚"
    author              = "áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"
  [ja.params.header]
    navbarTitle         = "é›ªã®ä¸–ç•Œ"
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true
  [ja.params.intro]
    header                = "é›ªã®ä¸–ç•Œ"
    paragraph             = "ç¤¾ä¼šå‡çµã—ã€åˆ†æã—ã¾ã—ãŸã€‚"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false
    [ja.params.intro.pic]
      src                 = "https://rsc.youronly.one/img/y/snoworld-square.webp"
      shape               = "circle"
      width               = ""
      alt                 = "é›ªã®ä¸–ç•Œ"
  [[ja.menu.main]]
    name              = "ãƒ›ãƒ¼ãƒ "
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1
  [[ja.menu.main]]
    name              = "ã‚«ãƒ†ã‚´ãƒª"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
  [[ja.menu.main]]
    name              = "ã‚¿ã‚°"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 6
  [[ja.menu.main]]
    name              = "YourOnly.Oneâ„¢"
    identifier        = "yoo-home"
    url               = "https://im.youronly.one/ja"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 8

[ko]
  languagename = "í•œêµ­ì–´"
  languageflag = "ğŸ‡°ğŸ‡·"
  languagecode = "ko"
  languagecodecountry = "kr"
  timeZone = "Asia/Seoul"
  weight = 150
  title = "ìŠ¤ë…¸ìš° ì›”ë“œ"
  [ko.params]
    description = "ì‚¬íšŒëŠ” ëƒ‰ë™ ë° ë¶„ì„."      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [ko.params.meta]
    description         = "ì‚¬íšŒëŠ” ëƒ‰ë™ ë° ë¶„ì„."
    author              = "áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"
  [ko.params.header]
    navbarTitle         = "ìŠ¤ë…¸ìš° ì›”ë“œ"
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true
  [ko.params.intro]
    header                = "ìŠ¤ë…¸ìš° ì›”ë“œ"
    paragraph             = "ì‚¬íšŒëŠ” ëƒ‰ë™ ë° ë¶„ì„."
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false
    [ko.params.intro.pic]
      src                 = "https://rsc.youronly.one/img/y/snoworld-square.webp"
      shape               = "circle"
      width               = ""
      alt                 = "ìŠ¤ë…¸ìš° ì›”ë“œ"
  [[ko.menu.main]]
    name              = "ì§‘"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1
  [[ko.menu.main]]
    name              = "ì¹´í…Œê³ ë¦¬"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
  [[ko.menu.main]]
    name              = "íƒœê·¸"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 6
  [[ko.menu.main]]
    name              = "YourOnly.Oneâ„¢"
    identifier        = "yoo-home"
    url               = "https://im.youronly.one/ko"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 8
