### Info: https://gohugo.io/content-management/multilingual/#configure-languages

#[en]
  #languageName = "English"
  #languageCode = "en"
  #languageCodeCountry = "xx"              # custom
  #languageFlag = "ğŸ‡¬ğŸ‡§"                     # custom
  #timeZone = "Etc/UTC"
  #tzOffset = "12h"                        # custom
  #tzAbbr = "UTC"                          # custom
  #tzAbbrTitle = ""                        # custom
  #weight = 110

[en-ph]
  languageName = "English (PH)"
  languageCode = "en-PH"
  languageCodeCountry = "ph"              # custom
  languageFlag = "ğŸ‡µğŸ‡­"                     # custom
  timeZone = "Asia/Manila"
  tzOffset = "8h"                        # custom
  tzAbbr = "ACT"                          # custom
  tzAbbrTitle = "Asean Common Time"                        # custom
  weight = 111
  [en-ph.params]
  [[en-ph.menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1
  [[en-ph.menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
  [[en-ph.menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 6
  [[en-ph.menu.main]]
    name              = "I'M YourOnly.One ğŸ”"
    identifier        = "yoo-home"
    url               = "https://im.youronly.one"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 8

#[fil]
  #languageName = "Filipino"
  #languageCode = "fil"
  #languageCodeCountry = "ph"              # custom
  #languageFlag = "ğŸ‡µğŸ‡­"                     # custom
  #timeZone = "Asia/Manila"
  #tzOffset = "8h"                        # custom
  #tzAbbr = "ACT"                          # custom
  #tzAbbrTitle = "Asean Common Time"                        # custom
  #weight = 120
  #title = ""
  #[fil.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"              # custom
  #languageFlag = "ğŸ‡µğŸ‡­"                     # custom
  #timeZone = "Asia/Manila"
  #tzOffset = "8h"                        # custom
  #tzAbbr = "ACT"                          # custom
  #tzAbbrTitle = "Asean Common Time"                        # custom
  #title = ""
  #[tl.tglg.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"              # custom
  #languageFlag = "ğŸ‡¨ğŸ‡³"                     # custom
  #timeZone = "Asia/Shanghai"
  #tzOffset = "8h"                        # custom
  #tzAbbr = "CST"                          # custom
  #tzAbbrTitle = "China Standard Time"                        # custom
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageCode = "zh-Hans"
  #languageCodeCountry = "cn"              # custom
  #languageFlag = "ğŸ‡¨ğŸ‡³"                     # custom
  #timeZone = "Asia/Shanghai"
  #tzOffset = "8h"                        # custom
  #tzAbbr = "CST"                          # custom
  #tzAbbrTitle = "China Standard Time"                        # custom
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ja]
  languageName = "æ—¥æœ¬èª"
  languageCode = "ja"
  languageCodeCountry = "jp"              # custom
  languageFlag = "ğŸ‡¯ğŸ‡µ"                     # custom
  timeZone = "Asia/Tokyo"
  tzOffset = "9h"                        # custom
  tzAbbr = "JST"                          # custom
  tzAbbrTitle = "Japan Standard Time"                        # custom
  weight = 140
  title = "é›ªã®ä¸–ç•Œ â„ï¸"
  [ja.params]
    description = "ç¤¾ä¼šå‡çµã—ã€åˆ†æã—ã¾ã—ãŸ"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [ja.params.meta]
    description         = "ç¤¾ä¼šå‡çµã—ã€åˆ†æã—ã¾ã—ãŸ"
    author              = "áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"
  [ja.params.header]
    navbarTitle         = "é›ªã®ä¸–ç•Œ"
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true
  [ja.params.intro]
    header                = "é›ªã®ä¸–ç•Œ"
    paragraph             = "ç¤¾ä¼šå‡çµã—ã€åˆ†æã—ã¾ã—ãŸ"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false
    [ja.params.intro.pic]
      src                 = "https://rsc.youronly.one/img/y/snoworld-square.webp"
      shape               = "circle"
      width               = ""
      alt                 = "é›ªã®ä¸–ç•Œ"
  [[ja.menu.main]]
    name              = "ãƒ›ãƒ¼ãƒ "
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1
  [[ja.menu.main]]
    name              = "ã‚«ãƒ†ã‚´ãƒª"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
  [[ja.menu.main]]
    name              = "ã‚¿ã‚°"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 6
  [[ja.menu.main]]
    name              = "I'M YourOnly.One ğŸ”"
    identifier        = "yoo-home"
    url               = "https://im.youronly.one"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 8

[ko]
  languageName = "í•œêµ­ì–´"
  languageCode = "ko"
  languageCodeCountry = "kr"              # custom
  languageFlag = "ğŸ‡°ğŸ‡·"                     # custom
  timeZone = "Asia/Seoul"
  tzOffset = "9h"                        # custom
  tzAbbr = "KST"                          # custom
  tzAbbrTitle = "Korea Standard Time"                        # custom
  weight = 150
  title = "ìŠ¤ë…¸ìš° ì›”ë“œ â„ï¸"
  [ko.params]
    description = "ì‚¬íšŒëŠ” ëƒ‰ë™ ë° ë¶„ì„"      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  [ko.params.meta]
    description         = "ì‚¬íšŒëŠ” ëƒ‰ë™ ë° ë¶„ì„"
    author              = "áœŒáœ“áœƒáœ’ (Yuki ãƒ» é›ªäº®)"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"
  [ko.params.header]
    navbarTitle         = "ìŠ¤ë…¸ìš° ì›”ë“œ"
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true
  [ko.params.intro]
    header                = "ìŠ¤ë…¸ìš° ì›”ë“œ"
    paragraph             = "ì‚¬íšŒëŠ” ëƒ‰ë™ ë° ë¶„ì„"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false
    [ko.params.intro.pic]
      src                 = "https://rsc.youronly.one/img/y/snoworld-square.webp"
      shape               = "circle"
      width               = ""
      alt                 = "ìŠ¤ë…¸ìš° ì›”ë“œ"
  [[ko.menu.main]]
    name              = "ì§‘"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1
  [[ko.menu.main]]
    name              = "ì¹´í…Œê³ ë¦¬"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
  [[ko.menu.main]]
    name              = "íƒœê·¸"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 6
  [[ko.menu.main]]
    name              = "I'M YourOnly.One ğŸ”"
    identifier        = "yoo-home"
    url               = "https://im.youronly.one"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 8
